name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build code with timestamp
        run: |
          echo "Build successful at $(date)"
          
      - name: Current time
        run: |
          echo "Current time is $(date)"
          
      - name: Display formatted timestamp
        run: |
          echo "Task completed"
